### ISSUE TITLE
Output Charset Problem 文字セット　プロブレム

### ISSUE THREAD

**Issue by j7168908jx** [julius-speech/dictation-kit#3]
I was trying dictation-kit with default settings, while the output seemingly to be messy.
I did not know which charset to use, as I had tried  `chcp 65001` (utf-8), `chcp 50220`(Japanese) and several other recommended charsets online.
私は先日デフォルトでキットをつかっていましたが、出力が文字化けしていました。
chcp 65001(utf-8)と50220が違っていますが、どの文字セットが正しいますか？

**Comment by ptytb** [comment]
The encoding is **Shift JIS** and its codepage is **932**

```
chcp 932
```

How I've figured that out:
`pip install guess`

```
import guess
guess.guess(open('00readme.txt', 'br').read())
```

Outputs 'Shift_JIS'

**Comment by j7168908jx** [comment]
Thanks a lot !
